version: '3'

services:
  patent-checker:
    container_name: patent-checker-container
    image: patent-checker-img
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Map localhost:3000 to container:3000
    env_file:
      - .env
